package pkg1.pkg1a.aed.vistas;

import pkg1.pkg1a.aed.modelos.BoletinPublicado;
import pkg1.pkg1a.aed.modelos.RevistaPublicada;
import java.util.ArrayList;

public class MainView extends javax.swing.JFrame {

    private ArrayList<RevistaPublicada> arrayRevistas = new ArrayList<>();
    private ArrayList<BoletinPublicado> arrayBoletines = new ArrayList<>();

    public MainView(ArrayList<RevistaPublicada> a, ArrayList<BoletinPublicado> b) {

        initComponents();
        this.setLocationRelativeTo(null);
        this.arrayRevistas = a;
        this.arrayBoletines = b;

    }

    public MainView(ArrayList a) {

        initComponents();
        this.setLocationRelativeTo(null);

        if (a.get(0).getClass().equals(RevistaPublicada.class)) {
            arrayRevistas = a;
        }

        if (a.get(0).getClass().equals(BoletinPublicado.class)) {
            arrayBoletines = a;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        gestionDeArticulosJLabel = new javax.swing.JLabel();
        barraMenumenuBar = new javax.swing.JMenuBar();
        revistasJMenu = new javax.swing.JMenu();
        registrarRevistasJMenuItem = new javax.swing.JMenuItem();
        mostrarRevistasJMenuItem = new javax.swing.JMenuItem();
        boletinesJMenu = new javax.swing.JMenu();
        registrarBoletinesJMenuItem = new javax.swing.JMenuItem();
        mostrarBoletinesJMenuItem = new javax.swing.JMenuItem();
        SalirJMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        menuPanel.setForeground(new java.awt.Color(102, 102, 102));

        gestionDeArticulosJLabel.setBackground(new java.awt.Color(76, 0, 2));
        gestionDeArticulosJLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        gestionDeArticulosJLabel.setForeground(new java.awt.Color(102, 5, 6));
        gestionDeArticulosJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gestionDeArticulosJLabel.setText("GESTION DE ARTICULOS");
        gestionDeArticulosJLabel.setToolTipText("");
        gestionDeArticulosJLabel.setAlignmentY(0.0F);
        gestionDeArticulosJLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(gestionDeArticulosJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(gestionDeArticulosJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        revistasJMenu.setText("Revistas");

        registrarRevistasJMenuItem.setText("Registrar");
        registrarRevistasJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarRevistasJMenuItemActionPerformed(evt);
            }
        });
        revistasJMenu.add(registrarRevistasJMenuItem);

        mostrarRevistasJMenuItem.setText("Mostrar");
        mostrarRevistasJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarRevistasJMenuItemActionPerformed(evt);
            }
        });
        revistasJMenu.add(mostrarRevistasJMenuItem);

        barraMenumenuBar.add(revistasJMenu);

        boletinesJMenu.setText("Boletines");

        registrarBoletinesJMenuItem.setText("Registrar");
        registrarBoletinesJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBoletinesJMenuItemActionPerformed(evt);
            }
        });
        boletinesJMenu.add(registrarBoletinesJMenuItem);

        mostrarBoletinesJMenuItem.setText("Mostrar");
        mostrarBoletinesJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarBoletinesJMenuItemActionPerformed(evt);
            }
        });
        boletinesJMenu.add(mostrarBoletinesJMenuItem);

        barraMenumenuBar.add(boletinesJMenu);

        SalirJMenu.setText("Salir");
        SalirJMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirJMenuMouseClicked(evt);
            }
        });
        barraMenumenuBar.add(SalirJMenu);

        setJMenuBar(barraMenumenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirJMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirJMenuMouseClicked

        this.dispose();
    }//GEN-LAST:event_SalirJMenuMouseClicked

    private void registrarRevistasJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarRevistasJMenuItemActionPerformed

        NewRevistaView nuevaRevista = new NewRevistaView(arrayRevistas, arrayBoletines);
        nuevaRevista.setVisible(true);

    }//GEN-LAST:event_registrarRevistasJMenuItemActionPerformed

    private void registrarBoletinesJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBoletinesJMenuItemActionPerformed

        NewBoletinView nuevoBoletin = new NewBoletinView(arrayBoletines, arrayRevistas);
        nuevoBoletin.setVisible(true);

    }//GEN-LAST:event_registrarBoletinesJMenuItemActionPerformed

    private void mostrarRevistasJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarRevistasJMenuItemActionPerformed

        ShowRevistasView nuevaMuestraRevistas = new ShowRevistasView(arrayRevistas, arrayBoletines);
        nuevaMuestraRevistas.setVisible(true);

    }//GEN-LAST:event_mostrarRevistasJMenuItemActionPerformed

    private void mostrarBoletinesJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarBoletinesJMenuItemActionPerformed

        BoletinesView nuevaMuestraBoletines = new BoletinesView(arrayBoletines, arrayRevistas);
        nuevaMuestraBoletines.setVisible(true);
    }//GEN-LAST:event_mostrarBoletinesJMenuItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu SalirJMenu;
    private javax.swing.JMenuBar barraMenumenuBar;
    private javax.swing.JMenu boletinesJMenu;
    private javax.swing.JLabel gestionDeArticulosJLabel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JMenuItem mostrarBoletinesJMenuItem;
    private javax.swing.JMenuItem mostrarRevistasJMenuItem;
    private javax.swing.JMenuItem registrarBoletinesJMenuItem;
    private javax.swing.JMenuItem registrarRevistasJMenuItem;
    private javax.swing.JMenu revistasJMenu;
    // End of variables declaration//GEN-END:variables
}
