package pkg1.pkg1a.aed.vistas;


import pkg1.pkg1a.aed.modelos.BoletinPublicado;
import pkg1.pkg1a.aed.modelos.RevistaPublicada;
import java.util.ArrayList;

public class ShowRevistasView extends javax.swing.JFrame {
    
    ArrayList<RevistaPublicada> revistasPublicadas = new ArrayList<>();
    ArrayList<BoletinPublicado> boletinesPublicados = new ArrayList<>();

    /**
     * Creates new form MostrarRevistas
     */
    public ShowRevistasView(ArrayList <RevistaPublicada> a, ArrayList <BoletinPublicado> b) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.revistasPublicadas = a;
        this.boletinesPublicados = b;
        
        for (RevistaPublicada revista : revistasPublicadas) {
        
            mostrarRevistasJTextArea.append(revista.toString());
            mostrarRevistasJTextArea.append("_________________________\n\n");
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mostrarRevistasJPanel = new javax.swing.JPanel();
        mostrarRevistasJLabel = new javax.swing.JLabel();
        mostrarRevistasJScrollPanel = new javax.swing.JScrollPane();
        mostrarRevistasJTextArea = new javax.swing.JTextArea();
        volverDeMostrarJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mostrarRevistasJPanel.setMaximumSize(new java.awt.Dimension(605, 420));
        mostrarRevistasJPanel.setMinimumSize(new java.awt.Dimension(605, 420));

        mostrarRevistasJLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        mostrarRevistasJLabel.setForeground(new java.awt.Color(187, 0, 255));
        mostrarRevistasJLabel.setText("REVISTAS");

        mostrarRevistasJTextArea.setEditable(false);
        mostrarRevistasJTextArea.setColumns(20);
        mostrarRevistasJTextArea.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mostrarRevistasJTextArea.setRows(5);
        mostrarRevistasJScrollPanel.setViewportView(mostrarRevistasJTextArea);

        volverDeMostrarJButton.setBackground(new java.awt.Color(78, 0, 255));
        volverDeMostrarJButton.setText("VOLVER");
        volverDeMostrarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverDeMostrarJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mostrarRevistasJPanelLayout = new javax.swing.GroupLayout(mostrarRevistasJPanel);
        mostrarRevistasJPanel.setLayout(mostrarRevistasJPanelLayout);
        mostrarRevistasJPanelLayout.setHorizontalGroup(
            mostrarRevistasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarRevistasJPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(mostrarRevistasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(volverDeMostrarJButton)
                    .addGroup(mostrarRevistasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mostrarRevistasJLabel)
                        .addComponent(mostrarRevistasJScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        mostrarRevistasJPanelLayout.setVerticalGroup(
            mostrarRevistasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarRevistasJPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(mostrarRevistasJLabel)
                .addGap(18, 18, 18)
                .addComponent(mostrarRevistasJScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(volverDeMostrarJButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostrarRevistasJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostrarRevistasJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverDeMostrarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverDeMostrarJButtonActionPerformed
       
        this.dispose();
        MainView nuevaPantallaPrincipal = new MainView(revistasPublicadas, boletinesPublicados);
        nuevaPantallaPrincipal.setVisible(true);
        
    }//GEN-LAST:event_volverDeMostrarJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel mostrarRevistasJLabel;
    private javax.swing.JPanel mostrarRevistasJPanel;
    private javax.swing.JScrollPane mostrarRevistasJScrollPanel;
    private javax.swing.JTextArea mostrarRevistasJTextArea;
    private javax.swing.JButton volverDeMostrarJButton;
    // End of variables declaration//GEN-END:variables
}
